name: Deploy documentation

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'Reference to build the docs from'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 10.7.0
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: Build docs
        working-directory: docs
        run: |
          pnpm install --frozen-lockfile
          pnpm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/.vitepress/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
